# This is a basic workflow to help you get started with Actions

name: CI

on: push

jobs:
  code_quality:
    runs-on: ubuntu-latest
    name: Checks with black, isort and possibly run tests
    container: python:3.9
    
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: staff
          POSTGRES_PASSWORD: postgres_password
          POSTGRES_PORT: 5432
          POSTGRES_USER: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      # Prepare test database
      - name: Install PostgreSQL client
        run: |
          apt-get update
          apt-get install --yes postgresql-client
      - name: Run migrations
        run: psql -f src/tests/db_migration.sql postgresql://postgres:postgres_password@postgres:5432/staff
      # Install packages and run tests vs code
      - name: Run script
        run: |        
          pip install starlite pytest SQLAlchemy psycopg2-binary asyncpg black
          black .
          py.test src/tests
        env:
          POSTGRES_HOST: postgres
          POSTGRES_DB: staff
          POSTGRES_PASSWORD: postgres_password
          POSTGRES_USER: postgres
