# This is a basic workflow to help you get started with Actions

name: CI

on: push

jobs:
  code_quality:
    runs-on: ubuntu-latest
    name: Checks with black, isort and possibly run tests
    container: python:3.9
    
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: staff
          POSTGRES_PASSWORD: staff_pwd
          POSTGRES_PORT: 5432
          POSTGRES_USER: staff
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run script
        run: |
        
          pip install starlite pytest SQLAlchemy psycopg2-binary
          # py.test src/tests
